### ISSUE TITLE
Invalid record in the index store

### ISSUE THREAD

**Issue by jolestar** [babylonlabs-io/staking-indexer#26]
The transaction
https://mempool.space/tx/2aeeddb97b138ea622d9194818fa2fa3d8432125032ac1aec32461ae91d80b78 with lock time 0, but it is in the index store and with `staking time` 64000.

```csv
2aeeddb97b138ea622d9194818fa2fa3d8432125032ac1aec32461ae91d80b78,0,864790,d3d09d91bab234a9d21bf3c98092e82aec525caf67566edace08918408819689,64000,b3a838cbf2e61f2ecadf9f5924710e66dcf8212545884853073fe62c5ff5b949,true,4994180
```

**Comment by gitferry** [comment]
This is a valid tx. Timelock within the bitcoin tx means it will be delayed until a certain block height before it will be included. The btcstaking frontend sets timelock to be 864789 to ensure that txs will be included after cap-2 is [activated](https://github.com/babylonlabs-io/networks/blob/28651b301bb2efa0542b2268793948bcda472a56/bbn-1/parameters/global-params.json#L30). It seems that this tx is sent via CLI.
